# Generated by Django 2.0.3 on 2018-03-12 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='topics',
            new_name='board',
        ),
    ]
